# ============================================================================
# MODULE: 23-help.sh
# Help text + show_help()
# Source lines 8366-8433 of main-v2.7.3
# ============================================================================

#  HELP
# ════════════════════════════════════════════════════════════════════════════════
show_help() {
  echo -e "${B}${BWHITE}AI CLI v${VERSION}${R} — Chat · Vision · Audio · Video · Canvas · TTM · MTM · Mtm"
  echo ""
  echo -e "${B}${BCYAN}ASKING & CHAT${R}"
  echo "  ai ask <prompt>                    — Ask a question"
  echo "  ai chat                            — Interactive chat"
  echo "  ai -C [name|auto] ask <prompt>     — Named chat (saved as JSONL)"
  echo "  ai chat-list / chat-show / chat-delete"
  echo "  ai code <prompt> [--run]           — Generate & optionally run code"
  echo "  ai pipe / review / explain / summarize / translate"
  echo ""
  echo -e "${B}${BCYAN}MEDIA${R}"
  echo "  ai audio transcribe/tts/analyze/convert/extract/ask/play/info"
  echo "  ai video analyze/transcribe/caption/extract/trim/convert/ask/summary"
  echo "  ai vision ask/ocr/caption/compare"
  echo "  ai imagine <prompt>"
  echo ""
  echo -e "${B}${BCYAN}TRAINED MODELS${R}"
  echo "  ${B}TTM${R}  (~179.35M — any GPU/CPU)      ai ttm <cmd>"
  echo "  ${B}MTM${R}  (~0.61B  — GTX 1080 fp16)     ai mtm <cmd>"
  echo "  ${B}Mtm${R}  (~1.075B — RTX 2080+ bf16)    ai Mtm <cmd>   (case sensitive!)"
  echo ""
  echo "  Commands: pretrain [c1] [c2]  enable  disable  train-now"
  echo "            upload [v]  create-repo  status  load [v]"
  echo "            set-custom1 <hf-id>   set-custom2 <hf-id>"
  echo ""
  echo "  Load shortcuts:"
  echo "    ai -TTM / ai -MTM / ai -Mtm"
  echo ""
  echo "  Pretraining datasets (6 standard + 2 custom):"
  echo "    1. TinyStories (6k)   2. CodeAlpaca (4k)   3. OpenOrca (3k)"
  echo "    4. The Stack Smol (3k) 5. FineWeb-Edu (4k) 6. Wikipedia-en (4k)"
  echo "    7. Custom 1 (user-defined HF id or local path)"
  echo "    8. Custom 2 (user-defined HF id or local path)"
  echo ""
  echo -e "${B}${BCYAN}CANVAS${R}"
  echo "  ai canvas new/open/ask/show/run/edit/diff/save/list/close"
  echo ""
  echo -e "${B}${BCYAN}MODELS${R}"
  echo "  ai model <name>  models  download  recommended  search-models  upload  model-info"
  echo "  ai model-create new/train/list/edit/info/delete/presets"
  echo ""
  echo -e "${B}${BCYAN}FINE-TUNING${R}"
  echo "  ai finetune prepare/start/merge/quantize/status"
  echo ""
  echo -e "${B}${BCYAN}SETTINGS${R}"
  echo "  ai config [key value]     ai keys [set KEY val]"
  echo "  ai session list/new/load  ai persona list/set/create"
  echo "  ai history [--search x]   ai status"
  echo "  ai install-deps [--cpu-only]"
  echo "  sudo ai uninstall       (v2.7.3: also works without dash)"
  echo "  ai alias set/list/del   (v2.7.3: user-defined command aliases)"
  echo "  ai error-codes          (v2.7.3: structured error code reference)"
  echo ""
  echo -e "${B}${BCYAN}GUI${R}"
  echo "  ai -gui / ai gui   — Python curses GUI (click or keyboard)"
  echo "  Themes: dark (default) · light · hacker · matrix"
  echo "  ai config gui_theme <theme>"
  echo ""
  echo -e "${B}${BCYAN}HF DATASET SYNC${R}"
  echo "  ai config hf_dataset_sync 1   — Enable chat sync to $HF_DATASET_REPO"
  echo "  ai config dataset_key <key>   — Set write-only HF key"
}

# ════════════════════════════════════════════════════════════════════════════════
#  MISC HELPERS (personas, sessions, config, history, etc.)
